### ISSUE TITLE
Will it implement for V2 scheduler?

### ISSUE THREAD

**Issue by cjdduarte** [ijgnd/anki__Deck_and_Card_Info_during_review#1]
Will it implement for V2 scheduler (Anki 2.1)?

**Comment by ijgnd** [comment]
the addon should work as expected in Anki 2.1 with the experimental scheduler. Keep in mind that I'm new to programming so there might be mistakes.

This add-on calls the scheduler only via `mw.col.sched`. Most of the calls to col.sched are with respect to my scheduler modifications which only work with the old scheduler and which are most likely not interesting for you and won't be called unless you have an add-on that creates a method `original_nextRevIvl`. So the part of general interest that depends on the scheduler is the attribute `mw.col.sched.today`.

But currently this is the same in the old and new scheduler. This is at least my understanding of the file collections.py (see [here](https://github.com/dae/anki/blob/master/anki/collection.py#L103)). collections.py just uses `self.sched.today` indepedent of the selected scheduler. 

I use 2.0. I just put the code into a file named `__init__.py` in a new folder in the addons21 folder and reviewed a few cards in 2.1 and everything seems to work.

Did I miss something?

**Comment by cjdduarte** [comment]
Tanks.
