### ISSUE TITLE
Bug report: add-on conflicted

### ISSUE THREAD

**Issue by ufo12413** [ijgnd/anki__Deck_and_Card_Info_during_review#6]
hi, ran into a bug today that will cause the card info window to appear blank and anki the program saying it runs into an error, right when i try to review my cards. 

Screenshot: https://imgur.com/g9EQFTm

Here is the debug window when the error pops up:
> Debug info:
> Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
> Platform: Mac 10.15.4
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-06-06 18:30:51
> Add-ons possibly involved: ⁨deck and card info sidebar during review, Review Heatmap⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt/webview.py", line 34, in cmd
>   File "aqt/webview.py", line 114, in _onCmd
>   File "aqt/webview.py", line 518, in _onBridgeCmd
>   File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-28>", line 2, in _linkHandler
>   File "anki/hooks.py", line 638, in decorator_wrapper
>   File "anki/hooks.py", line 635, in repl
>   File "/Users/itserichsieh/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 69, in heatmapLinkHandler
>     return None if not _old else _old(self, url)
>   File "aqt/overview.py", line 67, in _linkHandler
>   File "aqt/main.py", line 635, in moveToState
>   File "aqt/gui_hooks.py", line 1810, in __call__
>   File "/Users/itserichsieh/Library/Application Support/Anki2/addons21/673114053/__init__.py", line 85, in maybe_restore_sidebar
>     cs.show()
>   File "/Users/itserichsieh/Library/Application Support/Anki2/addons21/673114053/sidebar_base.py", line 79, in show
>     update_contents_of_sidebar(self)
>   File "/Users/itserichsieh/Library/Application Support/Anki2/addons21/673114053/sidebar_set_contents.py", line 27, in update_contents_of_sidebar
>     p = current_card_deck_properties(card)
>   File "/Users/itserichsieh/Library/Application Support/Anki2/addons21/673114053/card_deck_properties.py", line 93, in current_card_deck_properties
>     p["d_new_sep"] = conf['new']["separate"]  # unused
> KeyError: 'separate'

And here is a list of add-ons that i installed:

1. deck and card info sidebar during review
2. Frozen Fields
3. Image Occlusion Enhanced for Anki 21 alpha
4. load balancer
5. Review Heatmap
6. True retention by Card Maturity

Weirdly enough, the add-on that serves as the base of "deck and card info sidebar during review", "Extended Card Stats During Review", works fine for me. 
It says the error is possibly involving "Review Heatmap" or "deck and card info sidebar during review"; I've tried to disable/uninstall Review Heatmap, but the error kept popping up. So i assume it may be a bug in "deck and card info sidebar during review" add-on?

I would KILL to use the beautiful add-on that you guys created and have been helping to maintain it. Looking forward to any information to get rid of this error.

**Comment by ijgnd** [comment]
thanks for the report. Could you update and try again. Besides fixing this I made some other changes (that might introduce other bugs ...). If you run into any problems please let me know.

**Comment by ufo12413** [comment]
It works flawlessly for now! wow thanks for the speedy fix, will gladly report if another error pops up. Thanks again for all the hard work you put towards the add-on, it is much appreciated!
