### ISSUE TITLE
Suggestions: Put the full explanations of the abbreviations in the AnkiWeb description!

### ISSUE THREAD

**Issue by ufo12413** [ijgnd/anki__Deck_and_Card_Info_during_review#7]
Sometimes it gets pretty frustrating to guess what do all the abbreviations mean. Should consider putting them together in the description or on github or simply anywhere making it available for easy access.

**Comment by ijgnd** [comment]
I just updated the add-on: The abbreviations are now explained on ankiweb and on the side of the addon config window. Creating tooltips would be even better but that's too time consuming because the add-on was not designed for those so adding them later is too much work at the moment.
